package teambuilder;

public class Tiers 
{
	SpeciesList sl = new SpeciesList();
	public Species[] ubers = new Species[]{
			sl.arceus,sl.blaziken,sl.darkrai,sl.deoxys,sl.dialga,sl.genesect,sl.gengarmega,sl.giratina,sl.groudon,sl.hooh,sl.kangaskhanmega,sl.kyogre,sl.kyuremwhite,sl.lucariomega,sl.lugia,sl.mewtwo,sl.palkia,sl.rayquaza,sl.reshiram,sl.shayminsky,sl.xerneas,sl.yveltal,sl.zekrom
	};
	public Species[] ou = new Species[]{
			sl.aegislash,sl.azumarill,sl.bisharp,sl.breloom,sl.chansey,sl.charizard,sl.clefable,sl.conkeldurr,sl.diancie,sl.dragonite,sl.espeon,sl.excadrill,sl.ferrothorn,sl.garchomp,sl.gardevoir,sl.gengar,sl.gliscor,sl.greninja,sl.gyarados,sl.heatran,sl.keldeo,sl.kyuremblack,sl.landorus,sl.latias,sl.latios,sl.mamoswine,sl.mandibuzz,sl.manectric,sl.mawile,sl.medicham,sl.pinsir,sl.quagsire,sl.rotomwash,sl.scizor,sl.scolipede,sl.skarmory,sl.smeargle,sl.sylveon,sl.talonflame,sl.terrakion,sl.thundurus,sl.togekiss,sl.tyranitar,sl.vaporeon,sl.venusaur,sl.zapdos
	};
	public Species[] bl = new Species[]{
			sl.alakazammega,sl.crawdaunt,sl.diggersby,sl.gardevoirmega,sl.hawlucha,sl.heracrossmega,sl.klefki,sl.magnezone,sl.manaphy,sl.medichammega,sl.salamence,sl.staraptor,sl.thundurustherian,sl.tornadustherian,sl.venomoth,sl.volcarona,sl.weavile,sl.zygarde
	};
	public Species[] uu = new Species[]{
			sl.absol,sl.aerodactyl,sl.aggron,sl.alakazam,sl.ampharos,sl.arcanine,sl.azelf,sl.blastoise,sl.blissey,sl.celebi,sl.chandelure,sl.chesnaught,sl.cloyster,sl.crobat,sl.darmanitan,sl.donphan,sl.empoleon,sl.entei,sl.florges,sl.flygon,sl.forretress,sl.galvantula,sl.goodra,sl.gothitelle,sl.haxorus,sl.heracross,sl.hippowdon,sl.honchkrow,sl.houndoom,sl.hydreigon,sl.infernape,sl.jirachi,sl.kingdra,sl.krookodile,sl.lucario,sl.machamp,sl.metagross,sl.mew,sl.mienshao,sl.milotic,sl.nidoking,sl.nidoqueen,sl.noivern,sl.porygonz,sl.porygon,sl.raikou,sl.roserade,sl.rotomheat,sl.sableye,sl.scrafty,sl.shaymin,sl.slowbro,sl.snorlax,sl.starmie,sl.suicune,sl.swampert,sl.tentacruel,sl.toxicroak,sl.trevenant,sl.umbreon,sl.victini,sl.wobbuffet
	};
	public Species[] bl2 = new Species[]{
			sl.froslass, sl.kyurem, sl.shuckle, sl.tornadus
	};
	public Species[] ru = new Species[]{
			sl.abomasnow,sl.alomomola,sl.ambipom,sl.amoonguss,sl.aromatisse,sl.banette,sl.braviary,sl.bronzong,sl.cinccino,sl.clawitzer,sl.claydol,sl.cobalion,sl.cofagrigus,sl.cresselia,sl.delphox,sl.doublade,sl.drapion,sl.druddigon,sl.dugtrio,sl.durant,sl.eelektross,sl.emboar,sl.escavalier,sl.exploud,sl.fletchinder,sl.gallade,sl.gastrodon,sl.gligar,sl.golbat,sl.heliolisk,sl.hitmonchan,sl.hitmonlee,sl.hitmontop,sl.jellicent,sl.jolteon,sl.kabutops,sl.magneton,sl.meloetta,sl.moltres,sl.registeel,sl.reuniclus,sl.rhyperior,sl.rotommow,sl.sharpedo,sl.skuntank,sl.slowking,sl.tangrowth,sl.tyrantrum,sl.virizion,sl.whimsicott,sl.yanmega,sl.zoroark
	};
	public Species[] bl3 = new Species[]{
			sl.sigilyph
	};
	public Species[] nu = new Species[]{
			sl.accelgor,sl.altaria,sl.arbok,sl.archeops,sl.ariados,sl.armaldo,sl.articuno,sl.audino,sl.aurorus,sl.avalugg,sl.barbaracle,sl.basculin,sl.bastiodon,sl.beartic,sl.beautifly,sl.beedrill,sl.beheeyem,sl.bellossom,sl.bibarel,sl.bouffalant,sl.butterfree,sl.cacturne,sl.camerupt,sl.carbink,sl.carnivine,sl.carracosta,sl.castform,sl.chatot,sl.cherrim,sl.chimecho,sl.corsola,sl.cradily,sl.crustle,sl.cryogonal,sl.dedenne,sl.delcatty,sl.delibird,sl.dewgong,sl.ditto,sl.dodrio,sl.dragalge,sl.drifblim,sl.dunsparce,sl.dusknoir,sl.dustox,sl.electivire,sl.electrode,sl.emolga,sl.exeggutor,sl.farfetchd,sl.fearow,sl.feraligatr,sl.flareon,sl.floatzel,sl.furfrou,sl.furret,sl.garbodor,sl.gigalith,sl.girafarig,sl.glaceon,sl.glalie,sl.gogoat,sl.golduck,sl.golem,sl.golurk,sl.gorebyss,sl.gourgeist,sl.granbull,sl.grumpig,sl.hariyama,sl.heatmor,sl.huntail,sl.hypno,sl.illumise,sl.jumpluff,sl.jynx,sl.kangaskhan,sl.kecleon,sl.kingler,sl.klinklang,sl.kricketune,sl.lanturn,sl.lapras,sl.leafeon,sl.leavanny,sl.ledian,sl.lickilicky,sl.liepard,sl.lilligant,sl.linoone,sl.lopunny,sl.ludicolo,sl.lumineon,sl.lunatone,sl.luvdisc,sl.luxray,sl.magcargo,sl.magmortar,sl.malamar,sl.mantine,sl.maractus,sl.marowak,sl.masquerain,sl.meganium,sl.meowstic,sl.mesprit,sl.mightyena,sl.miltank,sl.minun,sl.mismagius,sl.mothim,sl.mrmime,sl.muk,sl.musharna,sl.ninetales,sl.ninjask,sl.noctowl,sl.octillery,sl.omastar,sl.pachirisu,sl.pangoro,sl.parasect,sl.pelipper,sl.persian,sl.phione,sl.pidgeot,sl.plusle,sl.politoed,sl.poliwrath,sl.primeape,sl.probopass,sl.purugly,sl.pyroar,sl.qwilfish,sl.raichu,sl.rampardos,sl.rapidash,sl.raticate,sl.regice,sl.regigigas,sl.regirock,sl.relicanth,sl.rotom,sl.samurott,sl.sandslash,sl.sawk,sl.sawsbuck,sl.sceptile,sl.seaking,sl.seismitoad,sl.serperior,sl.seviper,sl.shedinja,sl.shiftry,sl.simipour,sl.simisage,sl.simisear,sl.slaking,sl.slurpuff,sl.solrock,sl.spinda,sl.spiritomb,sl.stantler,sl.steelix,sl.stoutland,sl.stunfisk,sl.sudowoodo,sl.sunflora,sl.swalot,sl.swanna,sl.swellow,sl.swoobat,sl.tauros,sl.throh,sl.torkoal,sl.torterra,sl.tropius,sl.typhlosion,sl.unfezant,sl.unown,sl.ursaring,sl.uxie,sl.vanilluxe,sl.vespiquen,sl.victreebel,sl.vileplume,sl.vivillon,sl.volbeat,sl.wailord,sl.walrein,sl.watchog,sl.weezing,sl.whiscash,sl.wigglytuff,sl.wormadam,sl.xatu,sl.zangoose,sl.zebstrika
	};
	public Species[] nfe = new Species[]{
			sl.bayleef,sl.boldore,sl.braixen,sl.cascoon,sl.charmeleon,sl.clefairy,sl.combusken,sl.croconaw,sl.dewott,sl.dragonair,sl.duosion,sl.dusclops,sl.eelektrik,sl.electabuzz,sl.flaaffy,sl.floette,sl.fraxure,sl.frogadier,sl.gabite,sl.gloom,sl.gothorita,sl.graveler,sl.grotle,sl.grovyle,sl.gurdurr,sl.haunter,sl.herdier,sl.ivysaur,sl.jigglypuff,sl.kadabra,sl.kakuna,sl.kirlia,sl.klang,sl.krokorok,sl.lairon,sl.lampent,sl.lombre,sl.loudred,sl.luxio,sl.machoke,sl.magmar,sl.marill,sl.marshtomp,sl.metang,sl.metapod,sl.monferno,sl.nidorina,sl.nidorino,sl.nuzleaf,sl.palpitoad,sl.pidgeotto,sl.pignite,sl.pikachu,sl.piloswine,sl.poliwhirl,sl.prinplup,sl.pupitar,sl.quilava,sl.quilladin,sl.rhydon,sl.roselia,sl.seadra,sl.sealeo,sl.servine,sl.shelgon,sl.silcoon,sl.skiploom,sl.sliggoo,sl.spewpa,sl.staravia,sl.swadloon,sl.togetic,sl.tranquill,sl.vanillish,sl.vibrava,sl.vigoroth,sl.wartortle,sl.weepinbell,sl.whirlipede,sl.zweilous
	};
	public Species[] lcubers = new Species[]{
			sl.meditite,sl.murkrow,sl.scyther,sl.sneasel,sl.swirlix,sl.tangela,sl.yanma
	};
	public Species[] lc = new Species[]{
			sl.abra,sl.aipom,sl.amaura,sl.anorith,sl.archen,sl.aron,sl.axew,sl.azurill,sl.bagon,sl.baltoy,sl.barboach,sl.beldum,sl.bellsprout,sl.bergmite,sl.bidoof,sl.binacle,sl.blitzle,sl.bonsly,sl.bronzor,sl.budew,sl.buizel,sl.bulbasaur,sl.buneary,sl.bunnelby,sl.burmy,sl.cacnea,sl.caterpie,sl.charmander,sl.cherubi,sl.chespin,sl.chikorita,sl.chimchar,sl.chinchou,sl.chingling,sl.clamperl,sl.clauncher,sl.cleffa,sl.combee,sl.corphish,sl.cottonee,sl.cranidos,sl.croagunk,sl.cubchoo,sl.cubone,sl.cyndaquil,sl.darumaka,sl.deerling,sl.deino,sl.diglett,sl.doduo,sl.dratini,sl.drifloon,sl.drilbur,sl.drowzee,sl.ducklett,sl.duskull,sl.dwebble,sl.eevee,sl.ekans,sl.electrike,sl.elekid,sl.elgyem,sl.espurr,sl.exeggcute,sl.feebas,sl.fennekin,sl.ferroseed,sl.finneon,sl.flabebe,sl.fletchling,sl.foongus,sl.frillish,sl.froakie,sl.gastly,sl.geodude,sl.gible,sl.glameow,sl.goldeen,sl.golett,sl.goomy,sl.gothita,sl.grimer,sl.growlithe,sl.gulpin,sl.happiny,sl.helioptile,sl.hippopotas,sl.honedge,sl.hoothoot,sl.hoppip,sl.horsea,sl.houndour,sl.igglybuff,sl.inkay,sl.joltik,sl.kabuto,sl.karrablast,sl.klink,sl.koffing,sl.krabby,sl.kricketot,sl.larvesta,sl.larvitar,sl.ledyba,sl.lickitung,sl.lileep,sl.lillipup,sl.litleo,sl.litwick,sl.lotad,sl.machop,sl.magby,sl.magikarp,sl.magnemite,sl.makuhita,sl.mankey,sl.mantyke,sl.mareep,sl.meowth,sl.mienfoo,sl.mimejr,sl.minccino,sl.misdreavus,sl.mudkip,sl.munchlax,sl.munna,sl.natu,sl.nidoranf,sl.nidoranm,sl.nincada,sl.noibat,sl.nosepass,sl.numel,sl.oddish,sl.omanyte,sl.onix,sl.oshawott,sl.pancham,sl.panpour,sl.pansage,sl.pansear,sl.paras,sl.patrat,sl.pawniard,sl.petilil,sl.phanpy,sl.phantump,sl.pichu,sl.pidgey,sl.pidove,sl.pineco,sl.piplup,sl.poliwag,sl.ponyta,sl.poochyena,sl.porygon,sl.psyduck,sl.pumpkaboo,sl.purrloin,sl.ralts,sl.rattata,sl.remoraid,sl.rhyhorn,sl.riolu,sl.roggenrola,sl.rufflet,sl.sandile,sl.sandshrew,sl.scatterbug,sl.scraggy,sl.seedot,sl.seel,sl.sentret,sl.sewaddle,sl.shellder,sl.shellos,sl.shelmet,sl.shieldon,sl.shinx,sl.shroomish,sl.shuppet,sl.skiddo,sl.skitty,sl.skorupi,sl.skrelp,sl.slakoth,sl.slowpoke,sl.slugma,sl.smoochum,sl.snivy,sl.snorunt,sl.snover,sl.snubbull,sl.solosis,sl.spearow,sl.spheal,sl.spinarak,sl.spoink,sl.spritzee,sl.squirtle,sl.starly,sl.staryu,sl.stunky,sl.sunkern,sl.surskit,sl.swablu,sl.swinub,sl.taillow,sl.teddiursa,sl.tentacool,sl.tepig,sl.timburr,sl.tirtouga,sl.togepi,sl.torchic,sl.totodile,sl.trapinch,sl.treecko,sl.trubbish,sl.turtwig,sl.tympole,sl.tynamo,sl.tyrogue,sl.tyrunt,sl.vanillite,sl.venipede,sl.venonat,sl.voltorb,sl.vullaby,sl.vulpix,sl.wailmer,sl.weedle,sl.whismur,sl.wingull,sl.woobat,sl.wooper,sl.wurmple,sl.wynaut,sl.yamask,sl.zigzagoon,sl.zorua,sl.zubat
	};
}
